-- Grant privileges to ACTEUR
-- From CA
GRANT SELECT ON CA.gouvernement TO ACTEUR;
GRANT ON COMMIT REFRESH ON CA.gouvernement TO ACTEUR;
GRANT SELECT ON CA.section_budgetaire TO ACTEUR;
GRANT ON COMMIT REFRESH ON CA.section_budgetaire TO ACTEUR;
GRANT SELECT ON CA.unite_administrative TO ACTEUR;
GRANT ON COMMIT REFRESH ON CA.unite_administrative TO ACTEUR;
GRANT SELECT ON CA.localite TO ACTEUR;
GRANT ON COMMIT REFRESH ON CA.localite TO ACTEUR;
GRANT SELECT ON CA.groupe_service TO ACTEUR;
GRANT ON COMMIT REFRESH ON CA.groupe_service TO ACTEUR;
-- From CPP
GRANT SELECT ON CPP.categorie_budget TO ACTEUR;
GRANT ON COMMIT REFRESH ON CPP.categorie_budget TO ACTEUR;
GRANT SELECT ON CPP.usb TO ACTEUR;
GRANT ON COMMIT REFRESH ON CPP.usb TO ACTEUR;
GRANT SELECT ON CPP.action TO ACTEUR;
GRANT ON COMMIT REFRESH ON CPP.action TO ACTEUR;
-- From ADS
GRANT SELECT ON ADS.activites TO ACTEUR;
GRANT ON COMMIT REFRESH ON ADS.activites TO ACTEUR;
GRANT SELECT ON ADS.activite_de_service TO ACTEUR;
GRANT ON COMMIT REFRESH ON ADS.activite_de_service TO ACTEUR;
GRANT SELECT ON ADS.activite_de_recette TO ACTEUR;
GRANT ON COMMIT REFRESH ON ADS.activite_de_recette TO ACTEUR;
GRANT SELECT ON ADS.categorie_activite TO ACTEUR;
GRANT ON COMMIT REFRESH ON ADS.categorie_activite TO ACTEUR;
-- From NEC
GRANT SELECT ON NEC.nature_economique TO ACTEUR;
GRANT ON COMMIT REFRESH ON NEC.nature_economique TO ACTEUR;
GRANT SELECT ON NEC.nature_depense TO ACTEUR;
GRANT ON COMMIT REFRESH ON NEC.nature_depense TO ACTEUR;
GRANT SELECT ON NEC.table_referentiel TO ACTEUR;
GRANT ON COMMIT REFRESH ON NEC.table_referentiel TO ACTEUR;
GRANT SELECT ON NEC.version_referentiel TO ACTEUR;
GRANT ON COMMIT REFRESH ON NEC.version_referentiel TO ACTEUR;
-- From BUDGET
GRANT SELECT ON BUDGET.ligne_depense TO ACTEUR;
GRANT ON COMMIT REFRESH ON BUDGET.ligne_depense TO ACTEUR;
-- From PRT
GRANT SELECT ON PRT.msvc_module TO ACTEUR;
GRANT ON COMMIT REFRESH ON PRT.msvc_module TO ACTEUR;
GRANT SELECT ON PRT.msvc_service TO ACTEUR;
GRANT ON COMMIT REFRESH ON PRT.msvc_service TO ACTEUR;
GRANT SELECT ON PRT.msvc_menu TO ACTEUR;
GRANT ON COMMIT REFRESH ON PRT.msvc_menu TO ACTEUR;
GRANT SELECT ON PRT.msvc_action TO ACTEUR;
GRANT ON COMMIT REFRESH ON PRT.msvc_action TO ACTEUR;
-- From MEA
GRANT SELECT ON MEA.ligne_de_depenses TO ACTEUR;
GRANT ON COMMIT REFRESH ON MEA.ligne_de_depenses TO ACTEUR;
GRANT SELECT ON MEA.fonction_execution TO ACTEUR;
GRANT ON COMMIT REFRESH ON MEA.fonction_execution TO ACTEUR;