DELETE FROM AT_MV_SCRIPT;
DELETE FROM AT_MV;
DELETE FROM AT_TABLE_LOG;

-----------------------------------------------------------------------------------------------------------------------------------------------
-- AT_MV
-----------------------------------------------------------------------------------------------------------------------------------------------
Insert into AT_MV (NAME,ORDER_NUMBER,ENABLED,QUERY,DELETABLE_COLUMN,DELETABLE_MARKER) values ('VM_APP_EX_IMPUTATION',1,1,'SELECT * FROM UT_BIDF_TAMP.VA_ACTEUR_IMPUTATION@dblink_elabo_bidf t','CODE','DELETED');

-----------------------------------------------------------------------------------------------------------------------------------------------
-- AT_MV_SCRIPT
-----------------------------------------------------------------------------------------------------------------------------------------------
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','ALTER TABLE VM_APP_EX_IMPUTATION ADD CONSTRAINT VM_APP_EX_IMPUTATION_PK PRIMARY KEY (IDENTIFIANT)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_EXERCICE ON VM_APP_EX_IMPUTATION (EXERCICE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_CB ON VM_APP_EX_IMPUTATION (CATEGORIE_BUDGET ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_SECTION ON VM_APP_EX_IMPUTATION (SECTION ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_USB ON VM_APP_EX_IMPUTATION (USB ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_ACTION ON VM_APP_EX_IMPUTATION (ACTION ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_ACTIVITE ON VM_APP_EX_IMPUTATION (ACTIVITE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_NE ON VM_APP_EX_IMPUTATION (NATURE_ECONOMIQUE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_CA ON VM_APP_EX_IMPUTATION (CATEGORIE_ACTIVITE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_ND ON VM_APP_EX_IMPUTATION (NATURE_DEPENSE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_UA ON VM_APP_EX_IMPUTATION (UA ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_G ON VM_APP_EX_IMPUTATION (GESTIONNAIRE ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_RI ON VM_APP_EX_IMPUTATION (REGION_IDENTIFIANT ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_DI ON VM_APP_EX_IMPUTATION (DEPARTEMENT_IDENTIFIANT ASC)',null,1);
Insert into AT_MV_SCRIPT (MV,SCRIPT,ORDER_NUMBER,ENABLED) values ('VM_APP_EX_IMPUTATION','CREATE INDEX VMA_IMPUTATION_K_SPI ON VM_APP_EX_IMPUTATION (SOUS_PREFECTURE_IDENTIFIANT ASC)',null,1);


COMMIT;

BEGIN
	AP_CREATE_ALL_MV();
END;
/

CREATE OR REPLACE PROCEDURE AP_ACTUALIZE_MV_CALD_FRM_JOB AUTHID CURRENT_USER AS
BEGIN
    AP_ACTUALIZE_MV('VM_APP_EX_IMPUTATION');
END;
/

BEGIN
    DBMS_SCHEDULER.enable(name => '"AJ_ACTUALIZE_MV"');
END;
/